In [67]:
import numpy as np
import torch
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import random

# 这些东西代表的数值是相同的，但他们在计算机中存储的方式和表示方式有所不同
# 不同类型 有不同的操作

## python list
arr = [1,2,3]
## numpy 数组
np_arr = np.array([1,2,3])
## torch tensor
tensor_arr = torch.Tensor([1,2,3])


### 矩阵的转置

In [68]:
## 创建向量
na = np.array([[1,2,3,4]])
print(na)



## 转置
naT = na.T
print(naT)

## 再转置
naTT =naT.T

print(naTT)



[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


### 计算向量的点极


In [69]:

nv1 = np.array([1,2,3,4])
nv2= np.array([0,1,0,3])

np.dot(nv1,nv2)

14

### np.tile 复制

In [70]:
arr1 =  np.array([[1,2,3],[4,5,6]])

arr2 = np.tile(arr1,3)
arr3 = np.tile(arr1,(3,1))
print(arr2)
print(arr3)

[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


### tensor.mean() 求tensor 所有元素的平均值

In [71]:
d = torch.tensor([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
r = torch.mean(d.T.float())
r

tensor(2.)

In [72]:

tt = torch.tensor([[1,2,3],[2,3,4],[34,34,5],[32,5,6]])

tt[1,]
print(tt[0:2:1, 0:1])
print(tt[0:2])
print(tt[2:])

tensor([[1],
        [2]])
tensor([[1, 2, 3],
        [2, 3, 4]])
tensor([[34, 34,  5],
        [32,  5,  6]])


In [73]:
aaa =np.array([[1,2,3],[4,5,6],[7,8,9]])
aaa
print(aaa[:,0])

[1 4 7]


In [74]:

fig = plt.figure()

ax = Axes3D(fig)

X = np.arange(-2,2,0.1)

Y = np.arange(-2,2,0.1)
ax.scatter(X,Y,np.arange(-2,2,0.1))

plt.show()

<Figure size 640x480 with 0 Axes>

In [89]:
r =random.randrange(0,100,1)

r1= np.random.uniform()
r

61