In [1]:

import torch
import torch.nn as nn

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from torch.utils.data import DataLoader


In [2]:

import seaborn as sns
iris = sns.load_dataset('iris')
data = torch.tensor(iris[iris.columns[0:4]].values).float()

labels = torch.zeros(len(data),dtype=torch.long)

labels[iris.species == 'versicolor'] = 1
labels[iris.species == 'virginica'] = 2


In [6]:

fakedata= np.tile(np.array([1,2,3,4]),(10,1)) + np.tile(10*np.arange(1,11),(4,1)).T
fakelabels = np.arange(10) > 4

print(fakedata)
fakelabels

[[ 11  12  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]
 [ 41  42  43  44]
 [ 51  52  53  54]
 [ 61  62  63  64]
 [ 71  72  73  74]
 [ 81  82  83  84]
 [ 91  92  93  94]
 [101 102 103 104]]


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [10]:

fakedataLdr = DataLoader(fakedata,shuffle=True)

print(fakedataLdr)
print(fakedataLdr.batch_size)


for i ,oneSample in enumerate(fakedataLdr):
    print(i ,oneSample,oneSample.shape)

1


0 tensor([[61, 62, 63, 64]]) torch.Size([1, 4])
1 tensor([[41, 42, 43, 44]]) torch.Size([1, 4])
2 tensor([[11, 12, 13, 14]]) torch.Size([1, 4])
3 tensor([[71, 72, 73, 74]]) torch.Size([1, 4])
4 tensor([[21, 22, 23, 24]]) torch.Size([1, 4])
5 tensor([[101, 102, 103, 104]]) torch.Size([1, 4])
6 tensor([[91, 92, 93, 94]]) torch.Size([1, 4])
7 tensor([[51, 52, 53, 54]]) torch.Size([1, 4])
8 tensor([[31, 32, 33, 34]]) torch.Size([1, 4])
9 tensor([[81, 82, 83, 84]]) torch.Size([1, 4])


In [13]:
fakeDataset = torch.utils.data.TensorDataset(
    torch.Tensor(fakedata),
    torch.Tensor(fakelabels)
)

fakeDataset.tensors

fakedataLdr = DataLoader(fakeDataset,shuffle=True)

for dat,lab in fakedataLdr:
    print(dat,lab)

fakelabels

tensor([[61., 62., 63., 64.]]) tensor([1.])
tensor([[51., 52., 53., 54.]]) tensor([0.])
tensor([[11., 12., 13., 14.]]) tensor([0.])
tensor([[81., 82., 83., 84.]]) tensor([1.])
tensor([[41., 42., 43., 44.]]) tensor([0.])
tensor([[101., 102., 103., 104.]]) tensor([1.])
tensor([[71., 72., 73., 74.]]) tensor([1.])
tensor([[31., 32., 33., 34.]]) tensor([0.])
tensor([[21., 22., 23., 24.]]) tensor([0.])
tensor([[91., 92., 93., 94.]]) tensor([1.])


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [16]:

train_data,test_data,train_labels,test_labels = train_test_split(fakedata,fakelabels,test_size=.2)

train_data= torch.utils.data.TensorDataset(
    torch.Tensor(train_data),torch.Tensor(train_labels)
)

test_data= torch.utils.data.TensorDataset(
    torch.Tensor(test_data),torch.Tensor(test_labels)
)

train_loader = DataLoader(train_data,batch_size=4)

test_loader = DataLoader(test_data)


In [17]:


print("Training Data")

for batch ,label in train_loader:
    print(batch,label)


print('Testing data')

for batch,label in test_loader:
    print(batch,label)

    

Training Data
tensor([[21., 22., 23., 24.],
        [51., 52., 53., 54.],
        [71., 72., 73., 74.],
        [31., 32., 33., 34.]]) tensor([0., 0., 1., 0.])
tensor([[101., 102., 103., 104.],
        [ 81.,  82.,  83.,  84.],
        [ 91.,  92.,  93.,  94.],
        [ 41.,  42.,  43.,  44.]]) tensor([1., 1., 1., 0.])
Testing data
tensor([[61., 62., 63., 64.]]) tensor([1.])
tensor([[11., 12., 13., 14.]]) tensor([0.])


In [18]:
## 真实数据

# 分割数据
train_data,test_data,train_labels,test_labels = train_test_split(data,labels,train_size=.2)


## 转化成 pytorch datasets
train_data = torch.utils.data.TensorDataset(train_data,train_labels)
test_data = torch.utils.data.TensorDataset(test_data,test_labels)

# 最后 转化成 dataloader 对象
train_loader = DataLoader(train_data,shuffle=True,batch_size=12)
test_loader= DataLoader(test_data,batch_size=test_data.tensors[0].shape[0])


In [19]:
# 检查  数据批次的数量
for x,y in train_loader:
    print(x.shape,y.shape)

torch.Size([12, 4]) torch.Size([12])
torch.Size([12, 4]) torch.Size([12])
torch.Size([6, 4]) torch.Size([6])
