In [2]:

import numpy as np
import torch
import math
math.e

a = np.random.rand(10)
# np.where( )
print(a)


[0.0610282  0.24539898 0.2982673  0.07915169 0.0307521  0.20016229
 0.15371267 0.15613105 0.96713466 0.09784709]


In [3]:

t =torch.randn(20)
t1 = torch.randn(20)
r = np.where( t != t1)

print(r)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),)


In [4]:

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 4, 5, 6, 7])

# 找到两个数组中相同元素的索引
common_indices = np.where(arr1 == arr2)

# common_indices 包含了相同元素的索引
print(common_indices[0])

[0]


In [5]:

r = np.zeros((2,3,4))

r[1,1,2] =4
print(r)

# print(r[1,1,2])

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 4. 0.]
  [0. 0. 0. 0.]]]


In [6]:

# 创建示例数据
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])

# 使用 np.corrcoef 计算相关系数矩阵
correlation_matrix = np.corrcoef(x, y)

print(correlation_matrix)

[[ 1. -1.]
 [-1.  1.]]


### np.hstack 和 np.vstack

In [7]:
### hstack 水平链接2个数组

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

ab =np.hstack((a,b))
print(ab)
print(ab.T)

a_b = np.vstack((a,b))
print(a_b)
print(a_b.T)

# print(a_b[0])
# print("取0行和1行第2列",a_b[[0,1],2])
# ## 
# print(a_b[:1:])
# print(a_b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [8]:

t = torch.tensor([True,True,True])

t1 =torch.zeros(4)

t[True] = 1
t

tensor([True, True, True])

### np.pi

In [9]:
a1=np.sin(np.pi)
a2=np.sin(np.radians(180))
print(a1)
print(a2)

1.2246467991473532e-16
1.2246467991473532e-16


### ndarray 求cos

In [10]:
step =np.linspace(0,2*np.pi ,360)

r = np.cos(step)

r

array([ 1.        ,  0.99984685,  0.99938743,  0.99862189,  0.99755047,
        0.99617348,  0.99449136,  0.99250462,  0.99021387,  0.9876198 ,
        0.98472322,  0.981525  ,  0.97802614,  0.9742277 ,  0.97013084,
        0.96573683,  0.961047  ,  0.95606279,  0.95078573,  0.94521744,
        0.93935962,  0.93321407,  0.92678266,  0.92006737,  0.91307026,
        0.90579346,  0.89823922,  0.89040983,  0.8823077 ,  0.87393532,
        0.86529524,  0.85639011,  0.84722266,  0.8377957 ,  0.82811212,
        0.81817488,  0.80798702,  0.79755167,  0.78687202,  0.77595135,
        0.76479299,  0.75340038,  0.74177699,  0.72992638,  0.7178522 ,
        0.70555813,  0.69304794,  0.68032546,  0.66739459,  0.6542593 ,
        0.6409236 ,  0.62739157,  0.61366738,  0.59975521,  0.58565933,
        0.57138406,  0.55693376,  0.54231288,  0.52752588,  0.51257729,
        0.49747169,  0.48221372,  0.46680804,  0.45125937,  0.43557248,
        0.41975216,  0.40380328,  0.3877307 ,  0.37153936,  0.35

In [11]:

n1 =np.array([1,2,3,4])
n2 = np.array([5,6,7,8,9])

n3 =np.concatenate((n1,n2),axis=0)
print(n3)



[1 2 3 4 5 6 7 8 9]


In [12]:
print(math.e)
print(math.pi)

2.718281828459045
3.141592653589793


2