In [20]:

import torch
import torch.nn as nn

import torch.nn.functional as F



In [21]:

prob = .25

dropout = nn.Dropout(p = prob)

x = torch.ones(10)
y =dropout(x)

print(y)
print(torch.mean(y))


tensor([0.0000, 1.3333, 1.3333, 1.3333, 1.3333, 1.3333, 0.0000, 1.3333, 1.3333,
        1.3333])
tensor(1.0667)


In [24]:
dropout.eval()

## 可以手动切换
# y =dropout(x)
y = F.dropout(x,training= False)
print(x)
print(y*(1-prob))
print(torch.mean(y))


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0.7500, 0.7500, 0.7500, 0.7500, 0.7500, 0.7500, 0.7500, 0.7500, 0.7500,
        0.7500])
tensor(1.)


In [25]:


# 正在dropout
dropout.train()
y = dropout(x)
print(y)


# 没有dropout
dropout.eval()
y = dropout(x)
print(y)

#  任然没有dropout
y = dropout(x)
print(y)



tensor([1.3333, 1.3333, 0.0000, 1.3333, 0.0000, 1.3333, 0.0000, 1.3333, 1.3333,
        1.3333])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
