In [5]:

import numpy as np
from sklearn.decomposition import PCA


arr  = np.array([[.7,.7],[.3,.3]])
arr = arr.reshape(2, 2)  # 将arr转成2x2的矩阵

print(arr)

pca = PCA(n_components=1)  # 选择降维到1个主成分
arr_reduced = pca.fit_transform(arr)

print("Original array:")
print(arr)
print("Reduced array:")
print(arr_reduced)





[[0.7 0.7]
 [0.3 0.3]]
Original array:
[[0.7 0.7]
 [0.3 0.3]]
Reduced array:
[[ 0.28284271]
 [-0.28284271]]
